modLoader="javafml"
loaderVersion = "[${forge_version},)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Create: Tramways"
authors="Purple Create, C1200"
description='''
Create: Tramways adds a bunch of tram-related features. These features mainly
relate to signalling and signage used on UK tramways and railways.

a Purple Create mod
'''
logoFile = "logo.png"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange = "[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange = "${minecraft_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="${create_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="railways"
    mandatory=false
    versionRange="[${railways_version},)"
    ordering="NONE"
    side="BOTH"
